models/appointment.py
from enum import Enum
from database import db

class AppointmentStatus(Enum):
    OPEN = "OPEN" # Appointment is available for booking; the user can accept.
    CLOSED = "CLOSED" # Time slot is no longer available (e.g., double-booked).
    BOOKED = "BOOKED" # Appointment has been confirmed.
    COMPLETE = "COMPLETE" # Appointment has been completed
    DELETED = "DELETED" # Appointment has been deleted by the user.

class Appointment(db.Model):
    __tablename__ = 'appointments'

    id = db.Column(db.Integer, primary_key=True)
    customer_id = db.Column(db.Integer, db.ForeignKey('customers.id'))
    date = db.Column(db.Date, nullable=False)
    time = db.Column(db.Time, nullable=False)
    payed = db.Column(db.Boolean, default=False, nullable=False)
    status = db.Column(db.Enum(AppointmentStatus), default=AppointmentStatus.OPEN, nullable=False)
    payment_intent_id = db.Column(db.String(100), nullable=True)

    customer = db.relationship('Customer', back_populates='appointments')
    note_links = db.relationship('NoteLink', back_populates='appointment', cascade='all, delete-orphan')

    def set_status(self, status):
        if status not in AppointmentStatus:
            raise ValueError(f"Invalid status: {status}")
        self.status = status

models/appointment_form.py
from flask_wtf import FlaskForm
from wtforms import StringField, EmailField, HiddenField, TextAreaField, TelField
from wtforms.validators import DataRequired, Optional, Email

class AppointmentForm(FlaskForm):
    name = StringField('Full Name', validators=[DataRequired()])
    email = EmailField('Email', validators=[DataRequired(), Email()])
    phone_number = TelField('Phone Number', validators=[Optional()])
    street_address = StringField('Street Address', validators=[DataRequired()])
    date = HiddenField('Date', validators=[DataRequired()])
    time = HiddenField('Time', validators=[DataRequired()])
    notes = TextAreaField('Notes', validators=[Optional()])

models/invoice.py
from database import db
from datetime import datetime

class Invoice(db.Model):
    __tablename__ = 'invoices'

    id = db.Column(db.Integer, primary_key=True)
    customer_name = db.Column(db.String(255), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), default=1)
    provider_address = db.Column(db.String(255), default="Bemidji", nullable=False)
    customer_address = db.Column(db.String(255), nullable=False)
    issue_date = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
    total_amount = db.Column(db.Numeric(10, 2), default = 0.00, nullable=False)
    paid = db.Column(db.Boolean, default=False, nullable=False)
    booked = db.Column(db.Boolean, default=False, nullable=False)
    deleted = db.Column(db.Boolean, default=False, nullable=False)

    user = db.relationship('User', back_populates='invoices')

routes/dash.py
import stripe
from flask import Blueprint, jsonify, render_template, request, redirect, session, url_for
from flask_login import login_required, current_user
from sqlalchemy.exc import SQLAlchemyError

from datetime import datetime, timedelta

from database import db
from models.appointment import Appointment, AppointmentStatus
from models.customer import Customer
from models.note import Note
from models.place import Place
from models.note_link import NoteLink
from models.appointment_form import AppointmentForm
from models.service import Service
from models.invoice import Invoice

dash = Blueprint('dash', __name__)

@dash.route('/dashboard')
@login_required
def dashboard():
    return redirect(url_for('dash.appointments'))

@dash.route('/dashboard/appointments')
@login_required
def appointments():
    now = datetime.now().date()

    appointments = db.query(Appointment).options(
        db.joinedload((Appointment.customer, Customer.places)), # Load the Places associated with the Customer
        db.joinedload(Appointment.note_links) # Load NoteLinks, which access Notes
    ).filter(Appointment.status is not AppointmentStatus.DELETED).order_by(Appointment.date, Appointment.time).all()

    for appointment in appointments:
        # Soft delete past appointments
        if appointment.date < now:
            appointment.set_status(AppointmentStatus.COMPLETE)

    db.commit()

    valid_appointments = [appt for appt in appointments if appt.date >= now]

    for appointment in valid_appointments:
        name_parts = appointment.customer.name.split(' ', 1)
        appointment.fname = name_parts[0]
        appointment.lname = name_parts[1] if len(name_parts) > 1 else ""
        appointment.display_date = appointment.date.strftime('%d-%b-%Y')
        appointment.display_time = appointment.time.strftime('%I:%M %p')

    appointments_today = len([appt for appt in valid_appointments if appt.date == now])

    customers = db.query(Customer).options(
        db.joinedload(Customer.places)
    ).all()

    return render_template('manage_appointments.html',
                            appointments=valid_appointments,
                            appointments_today=appointments_today,
                            customers=customers,
                            user=current_user)

@dash.route('/dashboard/services')
@login_required
def services():
    services = db.query(Service).options(
        db.joinedload(Service.note_links)
    ).all()

    valid_services = [service for service in services if service.deleted != True]

    return render_template('manage_services.html',
                            services=valid_services,
                            user=current_user)

@dash.route('/dashboard/customers')
@login_required
def customers():
    customers = db.query(Customer).options(
        db.joinedload(Customer.note_links)
    ).all()

    return render_template('view_customers.html',
                            customers=customers,
                            user=current_user)

@dash.route('/dashboard/invoices')
@login_required
def invoices():
    invoices = db.query(Invoice).order_by(Invoice.issue_date).all()

    return render_template('view_invoices.html',
                            invoices=invoices,
                            user=current_user)

@dash.route('/dashboard/add_service', methods=['GET', 'POST'])
@login_required
def new_service():
    if request.method == 'POST':

        service = Service(
            name=request.form['name'],
            description=request.form['description'],
            price='is_addon' in request.form,
            is_package='is_package' in request.form
        )

        db.add(service)
        db.commit()

        return redirect(url_for('dash.services'))
    
    return render_template('new_service.html',
                            user=current_user)

@dash.route('/dashboard/edit_service/<int:service_id>', methods=['GET', 'POST'])
@login_required
def edit_service(service_id):
    service = db.query(Service).options(
        db.joinedload(Service.note_links).joinedload(NoteLink.note)
    ).get(service_id)

    if not service:
        return "Service not found", 404
    
    if request.method == 'POST':
        service.name = request.form['name']
        service.description = request.form['description']
        service.price = request.form['price']
        service.is_addon = 'is_addon' in request.form
        service.is_package = 'is_package' in request.form

        existing_note_links = {note_link.note.id: note_link for note_link in service.note_links}
        submitted_notes = request.form.getlist('notes')

        service.note_links = []

        for note_content in submitted_notes:
            if note_content:
                if existing_note_links:
                    # Get the first note ID to update
                    note_id = list(existing_note_links.keys())[0]
                    note_link = existing_note_links.pop(note_id)
                    note_link.note.content = note_content
                    service.note_links.append(note_link)
                else: # Create new note
                    new_note = Note(
                        content=note_content,
                        created_by=current_user.username
                    )

                    db.add(new_note)
                    db.commit()

                    new_note_link = NoteLink(
                        note_id=new_note.id,
                        appointment_id=None,
                        customer_id=None,
                        service_id=service.id
                    )

                    service.note_links.append(new_note_link)

        db.commit()
        return redirect(url_for('dash.services'))
    
    return render_template('edit_service.html', 
                            service=service,
                            user=current_user)

@dash.route('/dashboard/delete_service/<int:service_id>', methods=['POST'])
@login_required
def delete_service(service_id):
    if request.method == 'POST':
        service = db.query(Service).get(service_id)

        if service:
            service.deleted = True
            db.commit()

            return redirect(url_for('dash.services'))
        else:
            return jsonify({'error': 'Service not found.'}), 404

@dash.route('/dashboard/edit_customer/<int:customer_id>', methods=['GET', 'POST'])
@login_required
def edit_customer(customer_id):
    customer = db.query(Customer).options(
        db.joinedload(Customer.places),
        db.joinedload(Customer.note_links).joinedload(NoteLink.note)
    ).get(customer_id)

    if not customer:
        return "Customer not found", 404
    
    if request.method == 'POST':
        customer.name = request.form['name']
        customer.email = request.form['email']
        customer.phone_number = request.form['phone_number']
        customer.places[0].address = request.form['street_address']
        customer.places[0].longitude = request.form['longitude']
        customer.places[0].latitude = request.form['latitude']

        db.commit()

        existing_note_links = {note_link.note.id: note_link for note_link in customer.note_links}
        submitted_notes = request.form.getlist('notes')

        customer.note_links = []

        for note_content in submitted_notes:
            if note_content:
                if existing_note_links:
                    # Get the first note ID to update
                    note_id = list(existing_note_links.keys())[0]
                    note_link = existing_note_links.pop(note_id)
                    note_link.note.content = note_content
                    customer.note_links.append(note_link)
                else: # Create new note
                    new_note = Note(
                        content=note_content,
                        created_by='Admin'
                    )

                    db.add(new_note)
                    db.commit()

                    new_note_link = NoteLink(
                        note_id=new_note.id,
                        appointment_id=None,
                        customer_id=customer.id
                    )

                    customer.note_links.append(new_note_link)

        db.commit()
        return redirect(url_for('dash.dashboard'))
    
    return render_template('edit_customer.html', customer=customer)

@dash.route('/dashboard/edit_appointment/<int:appointment_id>', methods=['GET', 'POST'])
@login_required
def edit_appointment(appointment_id):
    appointment = db.query(Appointment).options(
        db.joinedload(Appointment.customer).joinedload(Customer.places),
        db.joinedload(Appointment.note_links).joinedload(NoteLink.note)
    ).get(appointment_id)

    if not appointment:
        return "Appointment not found", 404

    if request.method == 'POST':
        appointment_date = datetime.strptime(request.form.get('date'), '%Y-%m-%d').date()
        appointment_time = datetime.strptime(request.form.get('time'), '%H:%M').time()

        appointment.date = appointment_date
        appointment.time = appointment_time

        # Get existing notes mapped by their IDs
        existing_note_links = {note_link.note.id: note_link for note_link in appointment.note_links}
        submitted_notes = request.form.getlist('notes')

        appointment.note_links = []

        for note_content in submitted_notes:
            if note_content:
                if existing_note_links:
                    # Get the first note ID to update
                    note_id = list(existing_note_links.keys())[0]
                    note_link = existing_note_links.pop(note_id)
                    note_link.note.content = note_content
                    appointment.note_links.append(note_link)
                else: # Create new note
                    new_note = Note(
                        content=note_content,
                        created_by='Admin'
                    )

                    db.add(new_note)

routes/index.py
from flask import Blueprint, render_template

# Blueprint
main = Blueprint('main', __name__)

@main.route('/')
def index():
    return render_template('index.html')

routes/new_acc.py
from flask import Blueprint, render_template, redirect, url_for
from wtforms import StringField, PasswordField, SubmitField
from flask_wtf import FlaskForm
from wtforms.validators import DataRequired, Email
from werkzeug.security import generate_password_hash

from database import db
from models.user import User
from models.password import UserPassword

new_acc = Blueprint('new_acc', __name__)

class CreateAccountForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    email = StringField('E-mail', validators=[Email(), DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password', validators=[DataRequired()])
    submit = SubmitField('Create Account')

@new_acc.route('/create_account', methods = ['GET', 'POST'])
def create_user():
    form = CreateAccountForm()

    if form.validate_on_submit():

        if _username_exists(form.username.data) == True:
            form.username.errors.append("Username taken.")
        elif _email_exists(form.email.data) == True:
            form.username.errors.append("Email already in use.")
        elif _passwords_match(form.password.data, form.confirm_password.data) == False:
            form.username.errors.append("Passwords do not match.")
        else:
            new_pass = UserPassword(password_hash=generate_password_hash(form.password.data))
            db.add(new_pass)
            db.flush()

            new_user = User(
                username    = form.username.data,
                email       = form.email.data,
                password_id = new_pass.id
            )

            db.add(new_user)
            db.add(new_pass)
            db.commit()
            return redirect(url_for('auth.login'))
            
    return render_template('create_account.html', form=form)

def _username_exists(input_username : str) -> bool:
    if db.query(User).filter_by(username = input_username).first():
        return True
    else:
        return False
    
def _email_exists(input_email : str) -> bool:
    if db.query(User).filter_by(email = input_email).first():
        return True
    else:
        return False
    
def _passwords_match(password1 : str, password2 : str) -> bool:
    if password1 == password2:
        return True
    else:
        return False

templates/appointments.html
{% extends 'base.html' %}
{% block head %}
    <title>Book Appointment - Groomy</title>
    <style>
        .time-slots {
            display: grid;
            /* Creates 2 equal-width columns */
            grid-template-columns: repeat(2, 1fr);
            gap: 10px;
        }

        .slot-label {
            display: block;
            padding: 5px 10px;
            color: var(--black);
            box-shadow: var(--box-shadow);
            border-radius: 5px;
            cursor: pointer;
            text-align: center;
            text-transform: lowercase;
        }

        .slot-label input[type="radio"] {
            display: none;
        }

        .slot-label:hover {
            backdrop-filter: blur(10px);
        }

        .slot-label:has(input[type="radio"]:disabled),
        .slot-label:has(input[type="radio"]:disabled):hover {
            border: none;
            backdrop-filter: none;
            box-shadow: none;
            cursor: default;
        }

        .slot-label:has(input[type="radio"]:checked) {
            background: #7d2ecc;
            color: #fff;
        }

        .form-container {
            display: flex;
            flex-direction: row;
            column-gap: 20px;
            align-items: stretch;
            padding-bottom: 100px;
        }

        h2, h3, h4 {
            color: #192a3d;
        }

        #booking-form {
            border-radius: 0;
            padding: 0;
            background: none;
            width: auto;
            backdrop-filter: none;
            box-shadow: none;
            border: none;
            overflow-y: auto;
        }

        .form-group input {
            background: none;
            box-shadow: none;
            backdrop-filter: none;
            border-radius: 0;
        }

        .form-group textarea {
            border-radius: 0;
            background: none;
            border: none;
            backdrop-filter: none;
            box-shadow: none;
            padding: 0;
            margin: 0;
            max-width: none;
            min-height: unset;
            align-self: unset;
        }
        
        .form-group {
            position: relative;
            display: flex;
            align-items: center;
            font-size: 15px;
            margin-bottom: 10px;
        }

        .form-group:has(textarea) {
            position: relative;
            display: block;
        }

        .form-group:focus-within label,
        .form-group.not-empty label {
            opacity: 0;
            visibility: hidden;
            transform: translate3d(20px, 0, 0);
        }

        .form-group label {
            position: absolute;
            display: flex;
            align-items: center;
            margin: 0;
            padding: 0 15px;
            line-height: 1.5;
            font-size: inherit;
            cursor: text;
            color: #3a4f66;
            visibility: visible;
            transition: opacity 0.15s 
                cubic-bezier(0.455, 0.03, 0.515, 0.955),
                transform 0.15s cubic-bezier(0.455, 0.03, 0.515, 0.955),
                visibility 0.15s cubic-bezier(0.455, 0.03, 0.515, 0.955);
        }

        .form-group input,
        .form-group textarea {
            -webkit-appearance: none;
            appearance: none;
            width: 100%;
            height: 40px;
            font-size: inherit;
            margin: 0;
            padding: 0 12px;
            border-bottom: 2px solid #aaa;
            transition: all 0.12s cubic-bezier(0.455, 0.03, 0.515, 0.955);
        }

        .form-group input,
        .form-group textarea {
            color: #3a4f66;
        }

        .form-group input:focus,
        .form-group textarea:focus {
            outline: 0;
        }

        .form-group input:user-valid {
            border-bottom-color: #28b16d;
        }

        .form-group input:user-invalid {
            border-bottom-color: #cc0000;
        }

        .form-group textarea {
            min-height: 80px;
            resize: vertical;
            padding: 12px;
        }

        label .required {
            color: #cc0000;
        }

        .form-group:has(textarea) label {
            top: 7px;
        }

        button {
            margin: 0;
            background: none;
            backdrop-filter: none;
            box-shadow: none;
            border: none;
        }

        input[type="submit"],
        button[type="submit"] {
            position: absolute;
            right: 0;
            margin-top: 20px;
            display: inline-flex;
            align-items: center;
            justify-content: center;
            min-height: 40px;
            padding: 5px 20px;
            border: none;
            -webkit-appearance: none;
            appearance: none;
            text-align: center;
            border-radius: 5px;
            transition: all 0.2s ease;
            font-size: 15px;
            font-weight: 500;
            text-transform: capitalize;
            color: #fff;
            border: none;
            background-color: #7d2ecc;
        }

        input[type="submit"]:hover,
        button[type="submit"]:hover {
            transform: translate3d(0, -3px, 0);
            background-color: #7d2ecc;
        }

        input[type="submit"]::before,
        button[type="submit"]::before {
            display: block;
            position: absolute;
            z-index: -1;
            content: '';
            top: 12px;
            left: 10px;
            right: 10px;
            bottom: 0;
            opacity: 0;
            border-radius: inherit;
            background-color: #7d2ecc;
            transition: all 0.2s ease;
            filter: blur(11px);
        }

        input[type="submit"]:hover::before,
        button[type="submit"]:hover::before {
            opacity: 0.8;
        }

        @media (max-width: 768px) {
            .form-container {
                display: flex;
                flex-direction: column;
                column-gap: 20px;
                align-items: stretch;
                padding-bottom: 100px;
            }
        }
    </style>
{% endblock %}

{% block nav %}
    <li><a href="{{ url_for('main.index') }}">Home</a></li>
    <li><a href="{{ url_for('appts.appointments') }}">Book Appointment</a></li>
    <li><a href="#">About Us</a></li>
    <li><a href="#">Contact Us</a></li>
{% endblock %}

{% block content %}
    <section>
        <div class="form-container">
            <div class="calendar-container">
                <div class="calendar-base">
                    <div class="calendar-head">
                        <div class="calendar-year-select">
                            <div class="triangle-left"></div>
                            <div class="year"></div>
                            <div class="triangle-right"></div>
                        </div>
                        <div class="months">
                            <span class="month">Jan</span>
                            <span class="month">Feb</span>
                            <span class="month">Mar</span>
                            <span class="month">Apr</span>
                            <span class="month">May</span>
                            <span class="month">Jun</span>
                            <span class="month">Jul</span>
                            <span class="month">Aug</span>
                            <span class="month">Sep</span>
                            <span class="month">Oct</span>
                            <span class="month">Nov</span>
                            <span class="month">Dec</span>
                        </div>
                        <hr class="month-spacer">
                        <div class="days">SUN MON TUE WED THU FRI SAT</div>
                    </div>
                    <div class="calendar-body">
                        <div class="num-dates"></div>
                    </div>
                </div>
            </div>
            <div style="position: relative">
                <form id="booking-form" method="post" action="{{ url_for('appts.appointments') }}">
                    {{ form.hidden_tag() }}
                    <div class="form-group">
                        <label for="name">Full Name <b class="required">&nbsp;*</b></label>
                        {{ form.name(size=32) }}
                    </div>
                    <div class="form-group">
                        <label for="email">Email <b class="required">&nbsp;*</b></label>
                        {{ form.email(size=32) }}
                    </div>
                    <div class="form-group">
                        <label for="phone_number">Phone Number</label>
                        {{ form.phone_number(size=32, pattern='[0-9]{3}-[0-9]{3}-[0-9]{4}') }}
                    </div>
                    <div class="form-group">
                        <label for="street_address">Street Address <b class="required">&nbsp;*</b></label>
                        {{ form.street_address(size=32, id='street_address') }}
                    </div>
                    <input type="hidden" id="latitude" name="latitude">
                    <input type="hidden" id="longitude" name="longitude">
                    <div class="form-group">
                        <label for="notes">Notes</label>
                        {{ form.notes(size=32, cols='45', rows='8') }}
                    </div>
                </form>
                <h4 style="margin-bottom: 15px">Select Time</h4>
                <div class="time-slots"></div>
                <button type="submit" form="booking-form" value="Payment">Proceed</button>
            </div>
        </div>
    </section>
    <script src="{{ url_for('static', filename='js/calendar.js') }}"></script>
    <script>
        // Google Places Autocomplete
        function initAutocomplete() {
            const input = document.getElementById('street_address');
            const autocomplete = new google.maps.places.Autocomplete(input);
            autocomplete.setFields(['address_component', 'geometry']);

            input.placeholder = '';

            autocomplete.addListener('place_changed', function() {
                const place = autocomplete.getPlace();

                if (place.geometry) {
                    // Set latitude and longitude fields
                    document.getElementById('latitude').value = place.geometry.location.lat();
                    document.getElementById('longitude').value = place.geometry.location.lng();
                }
            });
        }
        
        window.onload = function() {
            initAutocomplete();
        }

        document.querySelectorAll('.form-group').forEach(group => {
            const input = group.querySelector('input, textarea');

            if (input) {
                if (input.id === 'phone_number') {
                    input.addEventListener('focus', function() {
                        input.setAttribute('placeholder', '123-456-7890');
                    });

                    input.addEventListener('blur', function() {
                        input.removeAttribute('placeholder');
                    });
                }

                if (input.id === 'email') {
                    input.addEventListener('focus', function() {
                        input.setAttribute('placeholder', 'john.doe@example.com');
                    });

                    input.addEventListener('blur', function() {
                        input.removeAttribute('placeholder');
                    });
                }

                input.addEventListener('input', () => {
                    if (input.value.trim() !== '') {
                        group.classList.add('not-empty');
                    } else {
                        group.classList.remove('not-empty');
                    }
                });

                if (input.value.trim() !== '') {
                    group.classList.add('not-empty');
                }
            }
        });
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB18HHJbiZIs6cT4GKPW0Vc_e6WQci8-ZE&loading=async&libraries=places&callback=initAutocomplete" async defer>
    </script>
{% endblock %}

templates/dash_confirmation.html
{% extends 'base-dash.html' %}
{% block head %}
    <title>Confirmation - Groomy</title>
{% endblock %}

{% block main %}
    <section>
        <p>The appointment has been successfully booked.</p>
        <p>Name: {{ appointment.name }}</p>
        <p>Date: {{ appointment.date }}</p>
        <p>Time: {{ appointment.time }}</p>
    </section>
{% endblock %}

templates/manage_services.html
{% extends 'base-dash.html' %}
{% block head %}
<title>Manage Services</title>
{% endblock %}

{% block main %}
<section class="flex-column">
    <div class="section-header">
        <h1>Manage Services</h1>
        <div class="section-header-options">
            <a href="{{ url_for('dash.new_service') }}" class="add">
                <svg width="20px" height="20px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M6 12H18M12 6V18" stroke="#ffffff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                </svg>
                <p>Add Service</p>
            </a>
        </div>
    </div>
    <table class="section-table">
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Price</th>
            <th>Addon</th>
            <th>Package Deal</th>
        </tr>
        {% if services %}
            {% for service in services %}
                <tr data-id="{{ service.id }}">
                    <td>{{ service.name }}</td>
                    <td class="description">{{ service.description }}</td>
                    <td class="price">{{ service.price }}</td>
                    <td>{{ service.is_addon }}</td>
                    <td>{{ service.is_package }}</td>
                    <td class="action">
                        <form id="delete-form-{{ service.id }}" method="POST" action="{{ url_for('dash.delete_service', service_id=service.id) }}" style="display: none;">
                            <input type="hidden" name="service_id" value="{{ service.id }}">
                        </form>
                        <a href="#" class="delete" onclick="return deleteItem('Are you sure you want to delete this service?', '{{ service.id }}')">
                            <svg width="20px" height="20px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M10 10V16M14 10V16M18 6V18C18 19.1046 17.1046 20 16 20H8C6.89543 20 6 19.1046 6 18V6M4 6H20M15 6V5C15 3.89543 14.1046 3 13 3H11C9.89543 3 9 3.89543 9 5V6" stroke="#BC4141" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                            </svg>
                        </a>
                        <a href="{{ url_for('dash.edit_service', service_id=service.id) }}" class="view-edit">
                            <svg width="20px" height="20px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" clip-rule="evenodd" d="M6.30147 15.5771C4.77832 14.2684 3.6904 12.7726 3.18002 12C3.6904 11.2274 4.77832 9.73158 6.30147 8.42294C7.87402 7.07185 9.81574 6 12 6C14.1843 6 16.1261 7.07185 17.6986 8.42294C19.2218 9.73158 20.3097 11.2274 20.8201 12C20.3097 12.7726 19.2218 14.2684 17.6986 15.5771C16.1261 16.9282 14.1843 18 12 18C9.81574 18 7.87402 16.9282 6.30147 15.5771ZM12 4C9.14754 4 6.75717 5.39462 4.99812 6.90595C3.23268 8.42276 2.00757 10.1376 1.46387 10.9698C1.05306 11.5985 1.05306 12.4015 1.46387 13.0302C2.00757 13.8624 3.23268 15.5772 4.99812 17.0941C6.75717 18.6054 9.14754 20 12 20C14.8525 20 17.2429 18.6054 19.002 17.0941C20.7674 15.5772 21.9925 13.8624 22.5362 13.0302C22.947 12.4015 22.947 11.5985 22.5362 10.9698C21.9925 10.1376 20.7674 8.42276 19.002 6.90595C17.2429 5.39462 14.8525 4 12 4ZM10 12C10 10.8954 10.8955 10 12 10C13.1046 10 14 10.8954 14 12C14 13.1046 13.1046 14 12 14C10.8955 14 10 13.1046 10 12ZM12 8C9.7909 8 8.00004 9.79086 8.00004 12C8.00004 14.2091 9.7909 16 12 16C14.2092 16 16 14.2091 16 12C16 9.79086 14.2092 8 12 8Z" fill="#000000"/>
                            </svg>
                        </a>
                    </td>
                </tr>
            {% endfor %}
        {% endif %}
    </table>
</section>
{% endblock %}